language: python
python:
- '3.8'
- '3.9'
install:
- pip3 install .
- python3 -m pip install --upgrade build
script:
- pytest
before_deploy: python3 -m build
deploy:
  provider: pypi
  username: __token__
  password:
    secure: SBjQ10GnTR2lx8RdJMDGSj+Hznee9eNEd3OkReO1jXren+op7sSQ5DrU+K5b2hsIE6cq7fJkjAfBZzSHPSJTb/cXreRBBtUQ5H8jRtkt8XL+EiQEfUT+HXwQgf+h/9Rfxj3FPiG3YudAsZTXzg7gXE+G+TRzuKwOFDwNTQWcvb9NihAto1Fb+JjW4MBa0pi18S3SQIAonZjQhBOY3FI+1YpgX/tNP6v9yKhzw2T2WlqiT+mrzwjww7dpWz4RbpQSr8P2aiPbt3SaKy5Upuw0v7uqJ6UsGfnfoWEu6lvhSoerxPUpN0ucm5oB3bH5Xv7+yGaxl2pkqQoT/205sOeJIX2hJmYXgeOclUOFPwXli2Yzm+dF1axsZvc2WS5Jn761RuknIqx3xmIeLwWqQEnQ5noaocxvxCte8XI7GjCjYa6F4qFonXlG8Bnw+GR6r92tP+8bU7osQmKQASRgSW9b1SRGgLxMzI153qIv+eG8N/bPzSMRuMPgLlDYCXLXupBw3gQ1XzbY2ACYQEWFkBZ3yY0AEqVQO+ZUffCD0fBlEezNQBYwbb/PY+HJWVJGa0McHE/ZhV6QQykR2b8cAILtutyrGYHukewygi6bCRXfB2PERPmB6gXywSd09L2qI1qm0WhBhNUtzcyIJtinpYZQPne7n4frgub8rFnYJX5bLzs=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_cleanup: true
  cleanup: true
