language: python
python:
- '3.8'
- '3.9'
install:
- pip3 install .
- python3 -m pip install --upgrade build
script:
- pytest
before_deploy: python3 -m build
deploy:
  provider: pypi
  username: __token__
  password:
    secure: twBsKrypKp33An1L9QjZM93PGmetSmeN5OqWQ2P5tMoT9rxuj0rMQ9XjZPTDJaf8AlQmgMApLntJs3LFl6OQBEn2yJOAw2oKZQen3nS9MrXavVWzaagwkCkBo92ZP5dodUYDIoD/OQ0pW+fIW+cWXDc232SYKzPpcZVJabXUSv+DZvyQP05iwtmGxT9a6BErm0aZkM95iiV7Y2Cab14/xpS0SPao2mVgVsd0X8wPovMSGfCZXu1m2ABPePU5wyJLvFm+3i/eihcopoMq9drpd9aTWNMQ8K1atYZWvYBlLWzNiuMV2XF9sJ7kTU0BO0ewF13mjNtWcdmbGdxY9ue3o8Ocg0zLPdqmdpHJ51LacqfgrK6qYM7vccUqm0h5KProiJ6HgmhF33YVGdRbALLvlLZnMdOpOWC14poPAmsrdGmth4KlK1FSYxTyyV8vP9PF7eO75tesr4lxl490WznnPYgNs49vmAB0IayEzFmQPugnrbkdW2F0OMtZ5l2zJ9nAy/KYrzBQZdpMs0AA75PBtRx1FLiCC9qzodrpS8nDqnxsjjVo0g2QCMJLNrGB+dX47c8KWV/w3Mf8D4D/o5H1fj7e+P7DeczoHr650ZYcLLxru1YoPURJ9UmiNo/79usnPZwhCMtZA1HY5K9KU4SLyVqf+LzyQj9LEenVihO2jpQ=
  on:
    tags: true
  cleanup: true
